### ISSUE TITLE
Add README details and repo style

### ISSUE THREAD

**Issue by emanuelfeld** [DCgov/Waze_TTC#2]
- [x] What information does it scrape?
- [x] How do you use this information?
- [x] Comments should go on repo issues page
- [x] Make name clearer (no acronyms), lower case, with dashes between words

**Comment by nunerakesh** [comment]
The code scraps the data from Waze portal that generates customized travel time data from user information. The routes are customized by Waze Inc per DDOT request. The code downloads travel time information on each route along with any incidents along the route.
